version: "3.9"
services:
  mongo:
    image: mongo:7.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: crud_db
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend-app
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      MONGO_URI: mongodb://mongo:27017/mean_project
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
