name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build & Push Backend
        run: |
          docker build -t svb18/backend-crud-app:latest ./backend
          docker push svb18/backend-crud-app:latest

      - name: Build & Push Frontend
        run: |
          docker build -t svb18/frontend-crud-app:latest ./frontend
          docker push svb18/frontend-crud-app:latest

      - name: SSH to Server & Update Docker
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_IP }}
          username: ubuntu
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/ubuntu/crud-dd-mean
            docker-compose pull
            docker-compose up -d
